# -*- coding: utf-8 -*-
"""# W5D3_Debug_Task

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1PMEv1h0_BfjjINAsIxMG8bhfFrnESbG_
"""

import numpy as np
import torch
import torch.nn as nn
from sklearn.preprocessing import StandardScaler

np.random.seed(42)
n_samples = 500

feature_1 = np.random.uniform(0, 1000, n_samples)
feature_2 = np.random.uniform(0, 1, n_samples)

X = np.column_stack([feature_1, feature_2])
y = (3 * feature_1 + 50 * feature_2 + 10).reshape(-1, 1)

scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

X_tensor = torch.tensor(X_scaled, dtype=torch.float32)
y_tensor = torch.tensor(y, dtype=torch.float32)


class SimpleNet(nn.Module):

  def __init__(self):
    super().__init__()
    self.fc1 = nn.Linear(2, 16)
    self.relu = nn.ReLU()
    self.fc2 = nn.Linear(16, 1)

  def forward(self, x):
    x = self.relu(self.fc1(x))
    x = self.fc2(x)
    return x


model = SimpleNet()
criterion = nn.MSELoss()
optimizer = torch.optim.Adam(model.parameters(), lr=0.01)

epochs = 50
for epoch in range(epochs):
  optimizer.zero_grad()
  predictions = model(X_tensor)
  loss = criterion(predictions, y_tensor)
  loss.backward()
  optimizer.step()

  if epoch % 5 == 0:
    print(f"Epoch {epoch:3d} | Loss: {loss.item():.4f}")

print(f"Loss النهائي: {loss.item():.4f}")
# 1. التشخيص والسبب الحقيقي (Root Cause)
# بعد فحص الكود والتأكد من أبعاد البيانات (Input/Output Shapes) والـ Layer Logic، اتضح إن السبب الرئيسي لثبات الـ Loss وعدم تعلم الشبكة هو مشكلتين مع بعض:

# فرق المقاييس بين البيانات (Unscaled Features): العمود الأول مقياسه كبير جداً (من 0 لـ 1000) بينما العمود الثاني صغير جداً (من 0 لـ 1). التباين الضخم دا بيخلي الـ Gradients غير مستقرة أثناء الـ Backpropagation والشبكة مابتطلبش تتعلم الخصائص الصغيرة.

# معدل تعلم عالي جداً (Extremely High Learning Rate): الكود كان بيستخدم lr = 1.0 مع SGD؛ القيمة دي ضخمة جداً بتخلي الـ Optimizer يقفز فوق الحل الصح (Overshooting) والـ Loss يثبت بدون ما يقل.

# 2. التعديلات اللي تمت (Applied Fixes)
# تعديل مقاييس البيانات: استخدمت StandardScaler عشان أخلي متوسط البيانات 0 والانحراف المعياري 1 لكافة الـ Features.

# ضبط الـ Optimizer والـ Learning Rate: غيرت الـ Optimizer لـ Adam واستخدمت معدل تعلم مناسب lr = 0.01 عشان نضمن تقارب الـ Loss بثبات وسرعة.

# 3. النت