# -*- coding: utf-8 -*-
"""w5_D4-D5

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1h0n-I-YK7NFT5Z7DRMsMq_tPMYgin1fo
"""

import torch
import torch.nn as nn
import torch.optim as optim
from torchvision import datasets, transforms
import matplotlib.pyplot as plt

transform = transforms.Compose([
    transforms.ToTensor(),
    transforms.Normalize((0.1307,), (0.3081,))
])

train_dataset = datasets.MNIST(root='./data', train=True, download=True, transform=transform)
test_dataset = datasets.MNIST(root='./data', train=False, download=True, transform=transform)

train_loader = torch.utils.data.DataLoader(dataset=train_dataset, batch_size=64, shuffle=True)
test_loader = torch.utils.data.DataLoader(dataset=test_dataset, batch_size=64, shuffle=False)

class EnhancedNN(nn.Module):
    def __init__(self, activation_type='relu'):
        super(EnhancedNN, self).__init__()
        self.flatten = nn.Flatten()
        self.fc1 = nn.Linear(784, 128)

        if activation_type == 'relu':
            self.activation = nn.ReLU()
        elif activation_type == 'sigmoid':
            self.activation = nn.Sigmoid()

        self.dropout = nn.Dropout(p=0.25)
        self.fc2 = nn.Linear(128, 10)

    def forward(self, x):
        x = self.flatten(x)
        x = self.fc1(x)
        x = self.activation(x)
        x = self.dropout(x)
        x = self.fc2(x)
        return x

def train_and_evaluate(activation_type='relu', epochs=5):
    model = EnhancedNN(activation_type=activation_type)
    criterion = nn.CrossEntropyLoss()
    optimizer = optim.Adam(model.parameters(), lr=0.001)

    train_losses = []
    val_losses = []

    for epoch in range(epochs):
        model.train()
        running_train_loss = 0.0
        for images, labels in train_loader:
            optimizer.zero_grad()
            outputs = model(images)
            loss = criterion(outputs, labels)
            loss.backward()
            optimizer.step()
            running_train_loss += loss.item()

        epoch_train_loss = running_train_loss / len(train_loader)
        train_losses.append(epoch_train_loss)

        model.eval()
        running_val_loss = 0.0
        with torch.no_grad():
            for images, labels in test_loader:
                outputs = model(images)
                loss = criterion(outputs, labels)
                running_val_loss += loss.item()

        epoch_val_loss = running_val_loss / len(test_loader)
        val_losses.append(epoch_val_loss)

        print(f"[{activation_type.upper()}] Epoch [{epoch+1}/{epochs}] | Train Loss: {epoch_train_loss:.4f} | Val Loss: {epoch_val_loss:.4f}")

    return train_losses, val_losses

relu_train, relu_val = train_and_evaluate('relu', epochs=5)
sigmoid_train, sigmoid_val = train_and_evaluate('sigmoid', epochs=5)

plt.figure(figsize=(12, 5))

plt.subplot(1, 2, 1)
plt.plot(relu_train, label='ReLU Train Loss', color='blue')
plt.plot(relu_val, label='ReLU Val Loss', color='blue', linestyle='--')
plt.title('ReLU with Dropout')
plt.xlabel('Epoch')
plt.ylabel('Loss')
plt.legend()
plt.grid(True)

plt.subplot(1, 2, 2)
plt.plot(sigmoid_train, label='Sigmoid Train Loss', color='orange')
plt.plot(sigmoid_val, label='Sigmoid Val Loss', color='orange', linestyle='--')
plt.title('Sigmoid with Dropout')
plt.xlabel('Epoch')
plt.ylabel('Loss')
plt.legend()
plt.grid(True)

plt.show()